services:
  api:
    build:
      context: .. # project root
      dockerfile: docker/Dockerfile
      target: runtime
    image: duration-predictor-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      ONNX_MODEL_PATH: ${ONNX_MODEL_PATH}
      PICKLE_MODEL_PATH: ${PICKLE_MODEL_PATH}
      METADATA_PATH: ${METADATA_PATH}
    restart: unless-stopped
  postgres:
    image: postgres:16.15-trixie
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped


  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.16.0-full
    depends_on:
      - postgres
      - minio
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - --artifacts-destination
      - s3://mlflow

    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
